#!/usr/bin/env python3
"""Replace the 稀有资源 (rare resources) icon with the app's Glossary glyph.

`record/assets/resource-icons/rare.png` currently shows the two characters 「稀有」
rendered as a bitmap.  This script renders the traced Glossary glyph into the same
64x64 transparent slot instead.

Because ``/record/assets/`` is listed in .gitignore, the PNG itself is a local
build artefact -- replacing it alone would not survive a regeneration.  So the
script also writes a self-contained generator to
``tools/build_rare_resource_icon.py`` (glyph data embedded, no dependency on
icon-extract/) that reproduces the same file.

    python icon-extract/make_rare_icon.py            # write
    python icon-extract/make_rare_icon.py --dry-run  # report only
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageChops, ImageDraw

HERE = Path(__file__).resolve().parent
# 脚本已从 <repo>/icon-extract/ 搬到 <repo>/tools/icon-extract/，仓库根因此多了一层。
# 注意：下面 TOOL_TEMPLATE 里的 parents[1] 是给 tools/ 下的生成物用的，不能跟着改。
ROOT = HERE.parents[1]
SOURCE_SVG = HERE / "svg" / "glossary.svg"
TARGET = ROOT / "record" / "assets" / "resource-icons" / "rare.png"
BACKUP = HERE / "backup" / "rare-original.png"
TOOL = ROOT / "tools" / "build_rare_resource_icon.py"

SIZE = 64          # matches the other resource icons
PAD = 2            # transparent margin, in output pixels
SS = 4             # supersampling
INK = (28, 26, 25)  # same near-black as core.png / echoes.png

TOKEN = re.compile(r"([MCLZ])|(-?\d*\.?\d+(?:e-?\d+)?)")


def flatten(d: str) -> list[list[tuple[float, float]]]:
    """Flatten the path into closed polygons, one per subpath."""
    vals: list = []
    for cmd, num in TOKEN.findall(d):
        vals.append(cmd if cmd else float(num))
    polys, cur = [], []
    i = 0
    x = y = 0.0
    start = (0.0, 0.0)
    while i < len(vals):
        t = vals[i]
        if t == "M":
            if len(cur) > 2:
                polys.append(cur)
            x, y = float(vals[i + 1]), float(vals[i + 2]); i += 3
            start = (x, y); cur = [(x, y)]
        elif t == "L":
            x, y = float(vals[i + 1]), float(vals[i + 2]); i += 3
            cur.append((x, y))
        elif t == "C":
            x1, y1 = float(vals[i + 1]), float(vals[i + 2])
            x2, y2 = float(vals[i + 3]), float(vals[i + 4])
            x3, y3 = float(vals[i + 5]), float(vals[i + 6]); i += 7
            for k in range(1, 17):
                t0 = k / 16.0
                mt = 1 - t0
                cur.append((mt**3 * x + 3 * mt**2 * t0 * x1 + 3 * mt * t0**2 * x2
                            + t0**3 * x3,
                            mt**3 * y + 3 * mt**2 * t0 * y1 + 3 * mt * t0**2 * y2
                            + t0**3 * y3))
            x, y = x3, y3
        elif t == "Z":
            i += 1
            if len(cur) > 2:
                polys.append(cur)
            cur = []
            x, y = start
        else:
            i += 1
    if len(cur) > 2:
        polys.append(cur)
    return polys


def render(d: str, vb: str, size: int = SIZE,
           ink: tuple[int, int, int] = INK) -> Image.Image:
    """Rasterise with the even-odd rule: XOR the fills of every subpath."""
    _x, _y, w, h = (float(v) for v in vb.split())
    s = (size - 2 * PAD) / max(w, h)
    ox = (size - w * s) / 2.0 + 0.5 * s      # path coords are pixel-centre based
    oy = (size - h * s) / 2.0 + 0.5 * s
    W = size * SS
    acc = Image.new("1", (W, W), 0)
    for poly in flatten(d):
        layer = Image.new("1", (W, W), 0)
        pts = [((px + 0.5) * s * SS + ox * SS, (py + 0.5) * s * SS + oy * SS)
               for px, py in poly]
        ImageDraw.Draw(layer).polygon(pts, fill=1)
        acc = ImageChops.logical_xor(acc, layer)
    alpha = acc.convert("L").resize((size, size), Image.LANCZOS)
    rgba = np.zeros((size, size, 4), dtype=np.uint8)
    rgba[..., 0], rgba[..., 1], rgba[..., 2] = ink
    rgba[..., 3] = np.asarray(alpha)
    return Image.fromarray(rgba, "RGBA")


TOOL_TEMPLATE = '''#!/usr/bin/env python3
"""Regenerate record/assets/resource-icons/rare.png from the app's Glossary glyph.

Generated by icon-extract/make_rare_icon.py; self-contained on purpose, because
/record/assets/ is in .gitignore -- the PNG is a local build artefact, so the
generator is what actually carries the change.

    python tools/build_rare_resource_icon.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageChops, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "record" / "assets" / "resource-icons" / "rare.png"

VIEW_BOX = {vb!r}
PATH_DATA = (
{path_lines}
)
SIZE = {size}
PAD = {pad}
SS = {ss}
INK = {ink!r}

TOKEN = re.compile(r"([MCLZ])|(-?\\d*\\.?\\d+(?:e-?\\d+)?)")


def flatten(d):
    vals = []
    for cmd, num in TOKEN.findall(d):
        vals.append(cmd if cmd else float(num))
    polys, cur = [], []
    i = 0
    x = y = 0.0
    start = (0.0, 0.0)
    while i < len(vals):
        t = vals[i]
        if t == "M":
            if len(cur) > 2:
                polys.append(cur)
            x, y = float(vals[i + 1]), float(vals[i + 2]); i += 3
            start = (x, y); cur = [(x, y)]
        elif t == "L":
            x, y = float(vals[i + 1]), float(vals[i + 2]); i += 3
            cur.append((x, y))
        elif t == "C":
            x1, y1 = float(vals[i + 1]), float(vals[i + 2])
            x2, y2 = float(vals[i + 3]), float(vals[i + 4])
            x3, y3 = float(vals[i + 5]), float(vals[i + 6]); i += 7
            for k in range(1, 17):
                t0 = k / 16.0
                mt = 1 - t0
                cur.append((mt**3 * x + 3 * mt**2 * t0 * x1 + 3 * mt * t0**2 * x2
                            + t0**3 * x3,
                            mt**3 * y + 3 * mt**2 * t0 * y1 + 3 * mt * t0**2 * y2
                            + t0**3 * y3))
            x, y = x3, y3
        elif t == "Z":
            i += 1
            if len(cur) > 2:
                polys.append(cur)
            cur = []
            x, y = start
        else:
            i += 1
    if len(cur) > 2:
        polys.append(cur)
    return polys


def main():
    tx, ty, w, h = (float(v) for v in VIEW_BOX.split())
    s = (SIZE - 2 * PAD) / max(w, h)
    ox = (SIZE - w * s) / 2.0 + 0.5 * s
    oy = (SIZE - h * s) / 2.0 + 0.5 * s
    W = SIZE * SS
    acc = Image.new("1", (W, W), 0)
    for poly in flatten(PATH_DATA):
        layer = Image.new("1", (W, W), 0)
        pts = [((px + 0.5) * s * SS + ox * SS, (py + 0.5) * s * SS + oy * SS)
               for px, py in poly]
        ImageDraw.Draw(layer).polygon(pts, fill=1)
        acc = ImageChops.logical_xor(acc, layer)
    alpha = acc.convert("L").resize((SIZE, SIZE), Image.LANCZOS)
    rgba = np.zeros((SIZE, SIZE, 4), dtype=np.uint8)
    rgba[..., 0], rgba[..., 1], rgba[..., 2] = INK
    rgba[..., 3] = np.asarray(alpha)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(rgba, "RGBA").save(TARGET)
    print(f"wrote {{TARGET.relative_to(ROOT)}} ({{SIZE}}x{{SIZE}}, ink {{INK}})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not SOURCE_SVG.exists():
        print(f"missing {SOURCE_SVG}", file=sys.stderr)
        return 1
    text = SOURCE_SVG.read_text(encoding="utf-8")
    vb = text.split('viewBox="', 1)[1].split('"', 1)[0]
    d = text.split('d="', 1)[1].rsplit('"', 1)[0]

    icon = render(d, vb)
    cov = (np.asarray(icon)[..., 3] > 10).mean()
    print(f"glossary glyph {vb} -> {icon.size} RGBA, coverage {cov:.3f}, ink {INK}")

    if args.dry_run:
        print("dry-run: nothing written")
        return 0

    if TARGET.exists() and not BACKUP.exists():
        BACKUP.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(TARGET, BACKUP)
        print(f"backed up original -> {BACKUP.relative_to(ROOT)}")
    icon.save(TARGET)
    print(f"wrote {TARGET.relative_to(ROOT)}")

    # keep the surrounding path data out of the template's own braces
    path_lines = "\n".join(f'    "{chunk}"' for chunk in
                           [d[i:i + 96] for i in range(0, len(d), 96)])
    TOOL.write_text(TOOL_TEMPLATE.format(vb=vb, path_lines=path_lines, size=SIZE,
                                         pad=PAD, ss=SS, ink=INK), encoding="utf-8")
    print(f"wrote {TOOL.relative_to(ROOT)} (self-contained generator)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
